FROM php:8.2-fpm-bullseye as php

COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y zip libpq-dev
RUN docker-php-ext-install pdo pdo_pgsql

RUN addgroup --system --gid 1000 video-game && adduser --system --uid 1000 --gid 1000 video-game
RUN mkdir /var/www/video-game
RUN chown -R video-game:video-game /var/www/video-game

USER video-game

WORKDIR /var/www/video-game

FROM php as php-ci

COPY --chown=video-game:video-game ../ .
RUN composer install --working-dir=/var/www/video-game

FROM php as php-dev

CMD ["php", "-S", "0.0.0.0:80", "-t", "public"]