### Get paginated video game list
< {%
    request.variables.set("page", "2")
    request.variables.set("limite", "3")
%}

GET http://localhost:80/api/video-games?page={{page}}&limit={{limite}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.page === 2);
        client.assert(response.body.limit === 3);
        client.assert(response.body.videoGames[0].id === 4);
        client.assert(response.body.videoGames[0].name === "God of War");
        client.assert(response.body.videoGames[0].genre[0] === "Action");
        client.assert(response.body.videoGames[0].genre[1] === "Adventure");
    })
%}

### Get paginated video game list without pagination params
GET http://localhost:80/api/video-games
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.page === 1);
        client.assert(response.body.limit === 5);
        client.assert(response.body.videoGames[0].id === 1);
        client.assert(response.body.videoGames[0].name === "The last of us");
        client.assert(response.body.videoGames[0].genre[0] === "Action");
        client.assert(response.body.videoGames[0].genre[1] === "Survival-Horror");
    })
%}