name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init project
        run: |
          docker compose up -d php-ci
      - name: Create test database
        run: |
          docker compose exec -T php-ci bin/console doctrine:database:create --if-not-exists --env=test |
          docker compose exec -T php-ci bin/console doctrine:schema:update --env=test --force
      - name: linter
        run: |
          docker compose exec -T --env PHP_CS_FIXER_IGNORE_ENV=1 php-ci vendor/bin/php-cs-fixer fix --dry-run
      - name: Run tests
        run: |
          docker compose exec -T php-ci vendor/bin/phpunit